-- List the number of films per category.
SELECT c.name AS category_name, COUNT(fc.film_id) AS number_of_films
FROM sakila.film_category AS fc
JOIN sakila.category AS c
ON c.category_id = fc.category_id
GROUP BY category_name;

-- Retrieve the store ID, city, and country for each store.
SELECT s.store_id AS store_ID, a.city_id AS city_ID, c.city as city_name, co.country as country_name
FROM sakila.store AS s
JOIN sakila.address AS a
ON s.address_id = a.address_id
JOIN sakila.city as c
ON c.city_id = a.city_id
JOIN sakila.country as co
ON co.country_id = c.country_id;

-- Calculate the total revenue generated by each store in dollars.
SELECT s.store_id AS store_ID, SUM(p.amount) AS revenue_in_dollars
FROM sakila.store AS s
JOIN sakila.staff AS st
ON s.store_id = st.store_id
JOIN sakila.payment as p
ON st.staff_id = p.staff_id
GROUP BY store_ID;

-- Determine the average running time of films for each category.
SELECT c.name AS category_name, ROUND(AVG(f.length)) AS avg_length
FROM sakila.category AS c
JOIN sakila.film_category AS fc
ON c.category_id = fc.category_id
JOIN sakila.film AS f
ON fc.film_id = f.film_id
GROUP BY category_name;